theme: jekyll-theme-cayman
title: Narmada
description: Needs and Available Resource Matching Assistant for Disasters and Adversities
google_analytics: UA-98481315-13
website: http://165.227.12.176/
demo_video: http://tinyurl.com/Narmada-demo
arxiv: https://arxiv.org/abs/1801.07757